[directory]
truncation_length = 8
fish_style_pwd_dir_length = 2

[username]
show_always = true

[hostname]
ssh_only = false

[shell]
disabled = false
bash_indicator = "bash "
fish_indicator = ""
zsh_indicator = "zsh "
format = "[$indicator]($style)"
